# Use cibuildwheel v2 to build wheels for Python 3.
# Based on https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels2

on:
  workflow_dispatch:
    inputs:
      cibw_build:
        description: 'CIBW_BUILD'
        default: '*'
      cibw_skip:
        description: 'CIBW_SKIP'
        # To limit the number of builds, skip most of musl-based versions,
        # older PyPy versions, and 32-bit builds.
        default: 'pp{37,38,39}-* cp{37,38,39}-musllinux* *_i686 *-win32'

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      env:
        CIBW_BUILD: ${{ github.event.inputs.cibw_build }}
        CIBW_SKIP: ${{ github.event.inputs.cibw_skip }}
        CIBW_ARCHS_MACOS: x86_64 arm64

    - run: ls -lh wheelhouse
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: wheels2
        path: wheelhouse/*.whl
